<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>73064648-6f37-4fcf-8b62-81a189976095</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PortfolioMS.Server.Application\PortfolioMS.Server.Application.csproj" />
    <ProjectReference Include="..\PortfolioMS.Server.Infrastructure\PortfolioMS.Server.Infrastructure.csproj" />
  </ItemGroup>

</Project>
